import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import { ApolloWrapper } from "@/lib/apollo-wrapper";
import apolloClient from "@/lib/apollo-client"; // Ensure this points to your Apollo Client instance
const inter = Inter({ subsets: ["latin"] });
import { ApolloProvider } from '@apollo/client';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ApolloProvider  client={apolloClient}>{children}</ApolloProvider>
      </body>

    </html>
  );
}
